"""
End-to-end retrieval test for the ACE artifact and rubric URI strategy.

This test exercises the EXACT repository-backed URI format generated by production:

  Artifact URI:  https://raw.githubusercontent.com/JimmyOgb/ACE/main/repository-artifacts/submissions/<hash>.txt
  Rubric URI:    https://raw.githubusercontent.com/JimmyOgb/ACE/main/repository-artifacts/academic-general-rubric-criteria.txt
  Profile URI:   https://raw.githubusercontent.com/JimmyOgb/ACE/main/repository-artifacts/academic-general-profile.txt

It also verifies the fallback Gist URI format:
  Fallback URI:  https://gist.githubusercontent.com/<owner>/<id>/raw/<file>

Because the test runs in the direct VM (no live blockchain transactions), the
web.get() calls are mocked to return the exact bytes that the real endpoints serve,
and the SHA-256 of those bytes is verified to match the hash committed on-chain —
exactly as `_retrieve_verified_source` does in production.

Test matrix:
  1. Primary artifact URI is true repository-backed raw.githubusercontent.com HTTPS.
  2. Artifact hash committed on-chain matches SHA-256 of exact uploaded bytes.
  3. Rubric URI is repository-backed raw.githubusercontent.com HTTPS.
  4. Rubric hash committed on-chain matches SHA-256 of repo file bytes.
  5. Full consensus execution: evaluators receive complete artifact & rubric text.
  6. Exactly five validators run and submission is finalized.
  7. Fallback Gist HTTPS URI format also passes full retrieval and hash verification.
"""

import hashlib
import json
import re

CONTRACT_PATH = "contracts/AcademicConsensusEngine.py"

# ---------------------------------------------------------------------------
# Simulated artifact upload (mirrors serverless upload via GitHub Contents API)
# ---------------------------------------------------------------------------

ARTIFACT_TEXT = (
    "This is a test academic paper submitted for E2E retrieval validation. "
    "It contains sufficiently unique content to verify that the contract "
    "retrieves exactly the bytes the frontend uploaded, hashes them, and "
    "confirms the hash against the committed on-chain value."
)
ARTIFACT_HASH_HEX = hashlib.sha256(ARTIFACT_TEXT.encode("utf-8")).hexdigest()
ARTIFACT_HASH = f"sha256:{ARTIFACT_HASH_HEX}"

# Primary repository-backed raw GitHub URL (committed via GitHub Contents API)
REPOSITORY_ARTIFACT_URI = (
    f"https://raw.githubusercontent.com/JimmyOgb/ACE/main/"
    f"repository-artifacts/submissions/{ARTIFACT_HASH_HEX}.txt"
)

# Fallback public Gist raw URL
SIMULATED_GIST_URI = (
    f"https://gist.githubusercontent.com/JimmyOgb/{ARTIFACT_HASH_HEX[:16]}/raw/ace-artifact-test.txt"
)

# ---------------------------------------------------------------------------
# Default rubric from raw.githubusercontent.com (mirrors frontend DEFAULT_RUBRIC)
# ---------------------------------------------------------------------------

RUBRIC_URI = (
    "https://raw.githubusercontent.com/JimmyOgb/ACE/main/"
    "repository-artifacts/academic-general-rubric-criteria.txt"
)
with open("repository-artifacts/academic-general-rubric-criteria.txt", "r", encoding="utf-8") as _f:
    RUBRIC_CRITERIA_TEXT = _f.read()

RUBRIC_HASH_HEX = hashlib.sha256(RUBRIC_CRITERIA_TEXT.encode("utf-8")).hexdigest()
RUBRIC_CRITERIA_HASH = f"sha256:{RUBRIC_HASH_HEX}"


def _mock_production_endpoints(direct_vm):
    """
    Mock gl.nondet.web.get() to return the exact bytes each URI would serve
    in production. This mirrors what the real GitHub servers return.
    """
    # Primary repository-backed artifact: raw.githubusercontent.com
    direct_vm.mock_web(
        rf"^{re.escape(REPOSITORY_ARTIFACT_URI)}$",
        {"status": 200, "body": ARTIFACT_TEXT},
    )
    # Fallback Gist URL
    direct_vm.mock_web(
        rf"^{re.escape(SIMULATED_GIST_URI)}$",
        {"status": 200, "body": ARTIFACT_TEXT},
    )
    # Rubric: raw.githubusercontent.com
    direct_vm.mock_web(
        rf"^{re.escape(RUBRIC_URI)}$",
        {"status": 200, "body": RUBRIC_CRITERIA_TEXT},
    )


def _build_e2e_submission(direct_vm, direct_deploy, direct_alice, artifact_uri=REPOSITORY_ARTIFACT_URI):
    """Deploy contract and register a submission using production URI formats."""
    direct_vm.sender = direct_alice
    _mock_production_endpoints(direct_vm)

    contract = direct_deploy(CONTRACT_PATH)

    # Register rubric with the real raw.githubusercontent.com URI
    rubric_id = contract.create_rubric(
        "Academic General Rubric",
        RUBRIC_URI,
        RUBRIC_CRITERIA_HASH,
        "research_paper",
        RUBRIC_CRITERIA_HASH,
        0, 100, 60, 3, False, 4,
    )

    # Create profile with real repository HTTPS URI
    profile_id = contract.create_profile(
        "Academic General Evaluation",
        "https://raw.githubusercontent.com/JimmyOgb/ACE/main/repository-artifacts/academic-general-profile.txt",
        "sha256:51cc7a807f921b2e8956d19b2fbfe61b6a9b93010389f9338c5d002e8320be69",
        "sha256:c738ad04cefd20ee3efb3a17f853c9ad6d419efc49e65931bc71d2be9ef9686c",
    )

    # Submit with repository-backed URI (production format)
    submission_id = contract.submit_for_evaluation(
        "E2E Retrieval Test Paper",
        f"sha256:{hashlib.sha256(ARTIFACT_TEXT.encode()).hexdigest()}",
        artifact_uri,
        ARTIFACT_HASH,
        rubric_id,
        "research_paper",
        f"https://raw.githubusercontent.com/JimmyOgb/ACE/main/repository-artifacts/submissions/{ARTIFACT_HASH_HEX}.json",
        f"sha256:{hashlib.sha256(b'{}').hexdigest()}",
    )

    return contract, submission_id, rubric_id, profile_id


def test_e2e_artifact_uri_is_real_https_not_urn_or_data(
    direct_vm, direct_deploy, direct_alice
):
    """Submitted artifact_uri must be real HTTPS, never urn:sha256: or data:."""
    contract, submission_id, _, _ = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice
    )
    sub = contract.get_submission(submission_id)

    assert sub.artifact_uri.startswith("https://"), (
        f"artifact_uri must be HTTPS, got: {sub.artifact_uri!r}"
    )
    assert not sub.artifact_uri.startswith("urn:"), (
        f"artifact_uri must not be urn:, got: {sub.artifact_uri!r}"
    )
    assert not sub.artifact_uri.startswith("data:"), (
        f"artifact_uri must not be data:, got: {sub.artifact_uri!r}"
    )
    assert not sub.artifact_uri.startswith("ace://"), (
        f"artifact_uri must not be ace://, got: {sub.artifact_uri!r}"
    )


def test_e2e_artifact_hash_matches_uploaded_bytes(
    direct_vm, direct_deploy, direct_alice
):
    """
    The artifact_hash committed on-chain must equal the SHA-256 of the bytes
    that gl.nondet.web.get(artifact_uri) returns.
    """
    contract, submission_id, _, _ = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice
    )
    sub = contract.get_submission(submission_id)

    retrieved_bytes = ARTIFACT_TEXT.encode("utf-8")
    computed_hash = hashlib.sha256(retrieved_bytes).hexdigest()
    committed_hex = sub.artifact_hash.replace("sha256:", "").strip().lower()

    assert computed_hash == committed_hex, (
        f"Hash mismatch: retrieved bytes hash {computed_hash!r} "
        f"!= committed {committed_hex!r}"
    )


def test_e2e_rubric_uri_is_raw_githubusercontent(
    direct_vm, direct_deploy, direct_alice
):
    """Rubric criteria URI must be raw.githubusercontent.com (not ace://)."""
    contract, submission_id, rubric_id, _ = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice
    )
    rubric = contract.get_rubric(rubric_id)

    assert rubric.description_uri.startswith("https://raw.githubusercontent.com/"), (
        f"description_uri must be raw.githubusercontent.com, got: {rubric.description_uri!r}"
    )
    assert "ace://" not in rubric.description_uri, (
        f"description_uri must not contain ace://"
    )


def test_e2e_rubric_hash_matches_repository_file(
    direct_vm, direct_deploy, direct_alice
):
    """
    The rubric criteria_hash committed on-chain must equal the SHA-256 of
    the bytes that would be retrieved from raw.githubusercontent.com.
    """
    contract, submission_id, rubric_id, _ = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice
    )
    rubric = contract.get_rubric(rubric_id)

    retrieved_bytes = RUBRIC_CRITERIA_TEXT.encode("utf-8")
    computed_hash = hashlib.sha256(retrieved_bytes).hexdigest()
    committed_hex = rubric.criteria_hash.replace("sha256:", "").strip().lower()

    assert computed_hash == committed_hex, (
        f"Rubric hash mismatch: retrieved hash {computed_hash!r} "
        f"!= committed {committed_hex!r}"
    )


def _evaluation_response(submission_id, rubric_id, validator_id, score=82):
    return {
        "schemaVersion": "0.1.0",
        "submissionId": submission_id,
        "rubricId": rubric_id,
        "validatorId": validator_id,
        "evaluationType": "research_paper",
        "criterionScores": [
            {
                "criterionId": f"criterion-{i}",
                "score": score // 4,
                "confidence": 8500,
                "rationale": "Verified criterion rationale.",
            }
            for i in range(1, 5)
        ],
        "overallRecommendation": "accepted",
        "overallConfidence": 8500,
        "summary": "E2E retrieval test: verified content.",
        "limitations": ["Test-only evaluation."],
        "fairnessChecklist": {"irrelevantStatusSignalsExcluded": True},
        "modelMetadata": {"promptVersion": "ace-e2e-test-v1"},
    }


def test_e2e_evaluator_receives_complete_artifact_and_rubric_with_five_validators(
    direct_vm, direct_deploy, direct_alice
):
    """
    Full E2E: verified artifact + rubric flow through evaluate_submission.

    Verifies:
    - artifact and rubric are retrieved through gl.nondet.web.get()
    - hash verification passes (fail-closed guards remain active)
    - exactly five evaluator prompts contain the complete artifact text
    - exactly five evaluator prompts contain the complete rubric text
    - consensus proceeds and the submission is finalized
    """
    contract, submission_id, rubric_id, profile_id = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice
    )
    contract.freeze_submission(submission_id)

    # Each evaluator prompt must contain the complete verified artifact and rubric
    for index, score in enumerate((82, 85, 83, 84, 82), start=1):
        prompt_regex = (
            rf"(?s)ACE_EVALUATION.*Evaluator ordinal: {index}.*"
            rf"\[SECTION A: VERIFIED SUBMITTED WORK\].*"
            rf"{re.escape(ARTIFACT_TEXT[:50])}.*"
            rf"\[SECTION B: COMPLETE VERIFIED RUBRIC\].*"
            rf"{re.escape(RUBRIC_CRITERIA_TEXT[:50])}"
        )
        direct_vm.mock_llm(
            prompt_regex,
            json.dumps(
                _evaluation_response(submission_id, rubric_id, f"ace-validator-{index}", score)
            ),
        )

    report_ids = [
        f"ace-report-{i}-{submission_id}-{str(contract.owner)}"
        for i in range(1, 6)
    ]
    direct_vm.mock_llm(
        r"ACE_CONSENSUS",
        json.dumps({
            "submissionId": submission_id,
            "rubricId": rubric_id,
            "reportIds": report_ids,
            "decision": "accepted",
            "confidence": 8400,
            "summary": "E2E consensus: all five validators agree.",
            "methodId": "ace-ai-consensus-v1",
        }),
    )

    consensus_id = contract.evaluate_submission(submission_id, profile_id)

    # Verify finalization
    assert consensus_id == f"ace-consensus-{submission_id}"
    assert contract.get_submission(submission_id).status == "finalized"

    # Verify exactly five reports
    stored_report_ids = contract.list_reports(submission_id, 0, 10)
    assert len(stored_report_ids) == 5, (
        f"Expected exactly 5 evaluator reports, got {len(stored_report_ids)}"
    )

    # Verify consensus result
    result = contract.get_consensus_result(consensus_id)
    assert result.decision == "accepted"
    assert result.status == "finalized"

    # Verify validator agreement runs correctly
    assert direct_vm.run_validator(index=0)
    assert direct_vm.run_validator(index=1)


def test_e2e_gist_fallback_uri_format_works_with_hash_verification(
    direct_vm, direct_deploy, direct_alice
):
    """Verify fallback Gist raw URLs also pass retrieval and hash verification."""
    contract, submission_id, rubric_id, profile_id = _build_e2e_submission(
        direct_vm, direct_deploy, direct_alice, artifact_uri=SIMULATED_GIST_URI
    )
    contract.freeze_submission(submission_id)

    for index, score in enumerate((82, 85, 83, 84, 82), start=1):
        prompt_regex = (
            rf"(?s)ACE_EVALUATION.*Evaluator ordinal: {index}.*"
            rf"\[SECTION A: VERIFIED SUBMITTED WORK\].*"
            rf"{re.escape(ARTIFACT_TEXT[:50])}"
        )
        direct_vm.mock_llm(
            prompt_regex,
            json.dumps(
                _evaluation_response(submission_id, rubric_id, f"ace-validator-{index}", score)
            ),
        )

    report_ids = [
        f"ace-report-{i}-{submission_id}-{str(contract.owner)}"
        for i in range(1, 6)
    ]
    direct_vm.mock_llm(
        r"ACE_CONSENSUS",
        json.dumps({
            "submissionId": submission_id,
            "rubricId": rubric_id,
            "reportIds": report_ids,
            "decision": "accepted",
            "confidence": 8400,
            "summary": "E2E fallback gist consensus: success.",
            "methodId": "ace-ai-consensus-v1",
        }),
    )

    consensus_id = contract.evaluate_submission(submission_id, profile_id)
    assert consensus_id == f"ace-consensus-{submission_id}"
    assert contract.get_submission(submission_id).status == "finalized"
